name: run tests

on:
  push:
    branches: [ master ]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: DEV
    permissions:
      id-token: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest-json-ctrf
      - name: Lint with flake8
        run: |
          flake8 ctrf --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: run tests
        run: |
          python -m pytest --ctrf $REPORT
        env:
            REPORT: 'test-results/report.json'

      - name: Generate Pretty Report
        if: always()
        run: |
          npx github-actions-ctrf test-results/report.json